<?php

return [
    'download_file_path_list' => [
        0 => [ 'no' => 1, 'index' => '1394', 'subject' => '1394' ],
        1 => [ 'no' => 2, 'index' => '3g', 'subject' => '3g' ],
        2 => [ 'no' => 3, 'index' => 'ad', 'subject' => 'ad' ],
        3 => [ 'no' => 4, 'index' => 'ahci', 'subject' => 'ahci' ],
        4 => [ 'no' => 5, 'index' => 'android', 'subject' => 'android' ],
        5 => [ 'no' => 6, 'index' => 'ap', 'subject' => 'ap' ],
        6 => [ 'no' => 7, 'index' => 'bt', 'subject' => 'bt' ],
        7 => [ 'no' => 8, 'index' => 'cam', 'subject' => 'cam' ],
        8 => [ 'no' => 9, 'index' => 'cir', 'subject' => 'cir' ],
        9 => [ 'no' => 10, 'index' => 'cr', 'subject' => 'cr' ],
        10 => [ 'no' => 11, 'index' => 'cs', 'subject' => 'cs' ],
        11 => [ 'no' => 12, 'index' => 'fp', 'subject' => 'fp' ],
        12 => [ 'no' => 13, 'index' => 'gps', 'subject' => 'gps' ],
        13 => [ 'no' => 14, 'index' => 'had', 'subject' => 'had' ],
        14 => [ 'no' => 15, 'index' => 'hotfix', 'subject' => 'hotfix' ],
        15 => [ 'no' => 16, 'index' => 'iffs', 'subject' => 'iffs' ],
        16 => [ 'no' => 17, 'index' => 'iha', 'subject' => 'iha' ],
        17 => [ 'no' => 18, 'index' => 'imsm', 'subject' => 'imsm' ],
        18 => [ 'no' => 19, 'index' => 'itb', 'subject' => 'itb' ],
        19 => [ 'no' => 20, 'index' => 'lan', 'subject' => 'lan' ],
        20 => [ 'no' => 21, 'index' => 'md', 'subject' => 'md' ],
        21 => [ 'no' => 22, 'index' => 'me', 'subject' => 'me' ],
        22 => [ 'no' => 23, 'index' => 'misc', 'subject' => 'misc' ],
        23 => [ 'no' => 24, 'index' => 'pci', 'subject' => 'pci' ],
        24 => [ 'no' => 25, 'index' => 'pn', 'subject' => 'pn' ],
        25 => [ 'no' => 26, 'index' => 'raid', 'subject' => 'raid' ],
        26 => [ 'no' => 27, 'index' => 'rs', 'subject' => 'rs' ],
        27 => [ 'no' => 28, 'index' => 'sata', 'subject' => 'sata' ],
        28 => [ 'no' => 29, 'index' => 'sba', 'subject' => 'sba' ],
        29 => [ 'no' => 30, 'index' => 'thunderbolt', 'subject' => 'thunderbolt' ],
        30 => [ 'no' => 31, 'index' => 'tm', 'subject' => 'tm' ],
        31 => [ 'no' => 32, 'index' => 'tp', 'subject' => 'tp' ],
        32 => [ 'no' => 33, 'index' => 'tpm', 'subject' => 'tpm' ],
        33 => [ 'no' => 34, 'index' => 'tv', 'subject' => 'tv' ],
        34 => [ 'no' => 35, 'index' => 'usb', 'subject' => 'usb' ],
        35 => [ 'no' => 36, 'index' => 'vga', 'subject' => 'vga' ],
        36 => [ 'no' => 37, 'index' => 'widi', 'subject' => 'widi' ],
        37 => [ 'no' => 38, 'index' => 'wl', 'subject' => 'wl' ],
        38 => [ 'no' => 39, 'index' => 'wm', 'subject' => 'wm' ],
        39 => [ 'no' => 40, 'index' => 'dptf', 'subject' => 'dptf' ],
        40 => [ 'no' => 41, 'index' => 'gna', 'subject' => 'gna' ],
        41 => [ 'no' => 42, 'index' => 'hdi', 'subject' => 'hdi' ]
    ],

    'permission_list' => [
        0 => 'user',
        1 => 'admin',
        2 => 'super',
        10 => 'super'
    ],

    'drivers_type_id_list'  => [
        0 => [ 'type_id' => 5, 'category_name' => 'Application' ],   
        1 => [ 'type_id' => 5, 'category_name' => 'Dragon Gaming Center' ],        
        2 => [ 'type_id' => 5, 'category_name' => 'ISCT' ],        
        3 => [ 'type_id' => 5, 'category_name' => 'SCM' ],        
        4 => [ 'type_id' => 5, 'category_name' => 'THX' ],        
        5 => [ 'type_id' => 5, 'category_name' => 'Tools' ],        
        6 => [ 'type_id' => 5, 'category_name' => 'SRS' ],        
        7 => [ 'type_id' => 5, 'category_name' => 'Hybrid Power' ],        
        8 => [ 'type_id' => 5, 'category_name' => 'KeyboradFirmware' ],        
        9 => [ 'type_id' => 5, 'category_name' => 'OA3.0 Tool' ],        
        10 => [ 'type_id' => 5, 'category_name' => 'PowerBoost' ],        
        11 => [ 'type_id' => 5, 'category_name' => 'Rapid Start Technology' ],       
        12 => [ 'type_id' => 5, 'category_name' => 'FSizing Options' ],
        13 => [ 'type_id' => 5, 'category_name' => 'Sound Blaster Cinema AP' ],        
        14 => [ 'type_id' => 5, 'category_name' => 'Sound Blaster Cinema EQ' ],        
        15 => [ 'type_id' => 5, 'category_name' => 'Super-Charger' ],        
        16 => [ 'type_id' => 34, 'category_name' => 'FingerPrinter' ],        
        17 => [ 'type_id' => 36, 'category_name' => 'Audio' ],        
        18 => [ 'type_id' => 37, 'category_name' => 'Chipset' ],        
        19 => [ 'type_id' => 38, 'category_name' => 'BlueTooth' ],        
        20 => [ 'type_id' => 39, 'category_name' => 'CardReader' ],        
        21 => [ 'type_id' => 40, 'category_name' => 'VGA' ],        
        22 => [ 'type_id' => 41, 'category_name' => 'LAN' ],        
        23 => [ 'type_id' => 43, 'category_name' => 'ClickPad' ],        
        24 => [ 'type_id' => 43, 'category_name' => 'TouchPad' ],        
        25 => [ 'type_id' => 44, 'category_name' => 'WLAN' ],        
        26 => [ 'type_id' => 47, 'category_name' => 'IRST' ],        
        27 => [ 'type_id' => 48, 'category_name' => '3G' ],        
        28 => [ 'type_id' => 49, 'category_name' => 'ME' ],        
        29 => [ 'type_id' => 56, 'category_name' => 'TPM' ],        
        30 => [ 'type_id' => 60, 'category_name' => 'USB 3.0' ],         
        31 => [ 'type_id' => 64, 'category_name' => 'GPS' ],        
        32 => [ 'type_id' => 67, 'category_name' => 'WIDI' ],        
        33 => [ 'type_id' => 69, 'category_name' => 'EC' ],        
        34 => [ 'type_id' => 71, 'category_name' => 'IFFS' ],        
        35 => [ 'type_id' => 72, 'category_name' => 'SBA' ],        
        36 => [ 'type_id' => 87, 'category_name' => 'Thunderbolt' ],        
        37 => [ 'type_id' => 91, 'category_name' => 'LTE' ],        
        38 => [ 'type_id' => 92, 'category_name' => 'NFC' ],        
        39 => [ 'type_id' => 101, 'category_name' => 'Dynamic Tuning' ]        
    ],

    'others_type_id_list'  => [
        0 => [ 'type_id' => 5, 'category_name' => 'Driver and Application' ], 
        1 => [ 'type_id' => 5, 'category_name' => 'Application' ],
        2 => [ 'type_id' => 5, 'category_name' => 'Tools' ],
        3 => [ 'type_id' => 28, 'category_name' => 'VBIOS' ],
        4 => [ 'type_id' => 28, 'category_name' => 'EC' ],
        5 => [ 'type_id' => 28, 'category_name' => 'EC Firmware' ],
        6 => [ 'type_id' => 35, 'category_name' => 'BIOS' ],
        7 => [ 'type_id' => 35, 'category_name' => 'BIOS and EC' ],
    ]
];